name: Build and Push CK3-Linter Docker Image

on:
  push:
    tags:
      - 'v*'  # Trigger this pipeline only on tags that start with 'v'

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout CK3-Linter repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build CK3-Linter Docker image
        run: |
          docker build -t thomasmldejong2004/ck3-lint/ck3-linter:${GITHUB_REF#refs/tags/} .
          docker build -t thomasmldejong2004/ck3-lint/ck3-linter:latest .

      - name: Push CK3-Linter Docker image to Docker Hub
        run: |
          docker push thomasmldejong2004/ck3-lint/ck3-linter:${GITHUB_REF#refs/tags/}
          docker push thomasmldejong2004/ck3-lint/ck3-linter:latest

      - name: Clean up Docker images
        run: |
          docker rmi thomasmldejong2004/ck3-lint/ck3-linter:${GITHUB_REF#refs/tags/}
          docker rmi thomasmldejong2004/ck3-lint/ck3-linter:latest
